# Changes here will be overwritten by Copier
_commit: 7cddaa1
_src_path: gh:ansible-selfhosted/selfhosted-role-template
author_company: ''
author_email: git@speakintel.net
author_name: SpeakinTelnet
collection_name: services
copyright_holder: SpeakinTelnet
license: MIT
related_url: https://docs.gitea.com/
repository_host: github.com
repository_url: https://github.com/ansible-selfhosted/selfhosted.services.gitea.git
role_name: gitea
short_description: A role to deploy Gitea using rootless Podman with systemd.
